
# Use this file to configure the Overcommit hooks you wish to use. This will
# extend the default configuration defined in:
# https://github.com/sds/overcommit/blob/master/config/default.yml
#
# At the topmost level of this YAML file is a key representing type of hook
# being run (e.g. pre-commit, commit-msg, etc.). Within each type you can
# customize each hook, such as whether to only run it on certain files (via
# `include`), whether to only display output if it fails (via `quiet`), etc.
#
# For a complete list of hooks, see:
# https://github.com/sds/overcommit/tree/master/lib/overcommit/hook
#
# For a complete list of options that you can use to customize hooks, see:
# https://github.com/sds/overcommit#configuration
#
# Uncomment the following lines to make the configuration take effect.

PreRebase:
  MergedCommits:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    parallelize: true
PreCommit:
  ALL:
    problem_on_unmodified_line: ignore
  TrailingWhitespace:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    parallelize: true
  LineEndings:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    parallelize: true
  RuboCop:
    enabled: true
    on_warn: fail # Treat all warnings as failures
    parallelize: true
    command: ["bundle", "exec", "rubocop"]
  Reek:
    enabled: true
    on_warn: fail
    parallelize: true
  Brakeman:
    enabled: true
    on_warn: fail
    parallelize: true
  BundleAudit:
    enabled: true
    flags: ["--update"]
    parallelize: true
  BundleOutdated:
    enabled: true
    on_warn: fail
    parallelize: true
  Flay:
    enabled: true
    on_warn: fail
    parallelize: true
  Fasterer:
    enabled: true
    exclude:
      - "vendor/**/*.rb"
      - "db/schema.rb"
    parallelize: true
  YamlSyntax:
    enabled: true
    on_warn: fail
    parallelize: true
  BundleCheck:
    enabled: true
    on_warn: fail
    parallelize: true
  HardTabs:
    enabled: true
    on_warn: fail
    parallelize: true
  MergeConflicts:
    enabled: true
    on_warn: fail
    parallelize: true
  RubyLint:
    enabled: true
    on_warn: fail
    parallelize: true
  RubySyntax:
    enabled: true
    on_warn: fail
    parallelize: true
